name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t my-jupyter-notebook

    - name: Run Docker container
      run: |
        CONTAINER_ID=$(docker run -d -p 8888:8888 my-jupyter-notebook)
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        NOTEBOOK_ADDRESS="http://$CONTAINER_IP:8888"
        echo "notebook_address=$NOTEBOOK_ADDRESS" >> $GITHUB_ENV
        echo "Jupyter Notebook is running at $NOTEBOOK_ADDRESS"

    - name: Get notebook address
      run: echo "Notebook address is ${{ env.notebook_address }}"
      shell: bash
