name: Launch Jupyter Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Start Docker container
      run: |
        docker pull jnishii/docker-gym-keras
        CONTAINER_ID=$(docker run -d -p 8888:8888 jnishii/docker-gym-keras)
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        echo "::set-output name=container_ip::$CONTAINER_IP"
    
    - name: Wait for Docker container to start
      run: |
        sleep 20
    
    - name: Display Jupyter Notebook URL
      run: |
        echo "Jupyter Notebook is running at http://${{ steps.build.outputs.container_ip }}:8888"
