name: Remote Jupyter Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gym==0.18.3 h5py==3.1.0 keras==2.6.0 keras-rl2==1.0.5 Pillow==9.0.0 tensorflow==2.7.0 numpy==1.22.3 jupyter
      
      - name: Install ngrok
        run: |
          curl -fsSL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz | tar xz -C /tmp
          sudo mv /tmp/ngrok /usr/local/bin/ngrok
          
      - name: Run Jupyter Notebook
        run: |
          mkdir notebooks
          jupyter notebook --ip=127.0.0.1 --port=8888 --no-browser --allow-root &
          sleep 10  # Wait for Jupyter Notebook to start
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok http 8888 > /dev/null &
          sleep 10  # Wait for ngrok to start
          
      - name: Get ngrok URL
        id: ngrok
        run: echo "::set-output name=url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
        
      - name: Save ngrok URL as environment variable
        run: echo "NGROK_URL=${{ steps.ngrok.outputs.url }}" >> $GITHUB_ENV
