name: Run Jupyter Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          pip install gym==0.25.2 h5py==3.10.0 keras==2.13.1 keras-rl2==1.0.4 Pillow==10.0.1 tensorflow==2.13.0 numpy==1.23.5 jupyter
          
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
          
      - name: Run Jupyter Notebook
        run: |
            mkdir notebooks
            jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root &
            sleep 10  # Wait for Jupyter Notebook to start
            ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
            ngrok http 8888 > /dev/null &
            sleep 10  # Wait for ngrok to start
        
      - name: Get ngrok URL
        id: ngrok
        run: echo "url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')" >> $GITHUB_ENV
        
      - name: Save state
        run: echo "JUPYTER_URL=${{ env.url }}" >> $GITHUB_ENV