name: Run Jupyter Notebook with ngrok

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t my-jupyter-notebook

    - name: Run Docker container
      run: |
        CONTAINER_ID=$(docker run -d -p 8888:8888 my-jupyter-notebook)
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        NOTEBOOK_ADDRESS="http://$CONTAINER_IP:8888"
        echo "notebook_address=$NOTEBOOK_ADDRESS" >> $GITHUB_ENV
        echo "Jupyter Notebook is running at $NOTEBOOK_ADDRESS"

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Start ngrok
      run: ./ngrok http 8888 &
    
    - name: Wait for ngrok tunnel
      run: sleep 10

    - name: Get ngrok tunnel URL
      id: ngrok
      run: echo "::set-output name=ngrok_url::$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

    - name: Display ngrok tunnel URL
      run: echo "Ngrok tunnel is ${{ steps.ngrok.outputs.ngrok_url }}"
